import pandas as pd
from rdkit import Chem

def is_valid_smiles(smiles):
        mol = Chem.MolFromSmiles(smiles)
        return mol is not None

df = pd.read_csv("tool\小分子库.csv")
# 删除无法处理与空的分子
df_examine = df[['SMILES']].dropna().copy()
df_examine['valid'] = df_examine['SMILES'].apply(is_valid_smiles)
df_examine = df_examine[df_examine['valid']].drop(columns=['valid'])

# 生成文件
new_df = pd.DataFrame({
    "smiles": df_examine["SMILES"],
    "protein_sequence": "MTSASNPPAFRLETSDGDEEGSAEVNKGKNEPPPMESPFQGEDRNFSPQIKVNLNYRKGLGPSQQDPNRFDRDRLFSVVSRGVPEELTGLLEYLRRTSKYLTDSAYTEGSTGKTCLMKAVLNLQDGVNACILPLLQIDRDSGNPQPLVNAQCTDEFYRGHSALHIAIEKRSLWCVKLLVENGANVHIRACGRFFQKHQGTCFYFGELPLSLAACTKQWDVVTYLLENPHQPASLEATDSLGNTVLHALVMIADNSPENSALVIHMYDSLLQMGARLCPTVQLEDICNHQGLTPLKLAAKEGKIEIFRHILQREFSGLYQPLSRKFTEWCYGPVRVSLYDLSSVDSWEKNSVLEIIAFHCKSPHRHRMVVLEPLNKLLQEKWDRLIPRFFFNFACYLVYMIIFTIVAYHQPSLEQPAIPSSKATFGDSMLLLGHILILLGGIYLLLGQLWYFWRRRLFIWISFMDSYFEILFLVQALLTVLSQVLRFVETEWYLPLLVSSLVLGWLNLLYYTRGFQHTGIYSVMIQKVILRDLLRFLLVYLVFLFGFAVALVSLSREARSPKAPEDSNTTVTEKPTLGQEEEPVPYGGILDASLELFKFTIGMGELAFQEQLRFRGVVLLLLLAYVLLTYVLLLNMLIALMSETVNSVATDSWSIWKLQKAISVLEMENGYWWCRRKRHRAGRLLKVGTKGDGIPDERWCFRVEEVNWAAWEKTLPTLSEDPSGAGITGYKKNPTSKPGKNSASEEDHLPLQVLQSH"  
})

print(f"处理后有效的SMILES数量为: {len(new_df)}，无效SMILES数量: {len(df) - len(new_df)}")
# 保存
new_df.to_csv("tool\sample_input.csv", index=False)
